import {test,expect} from '@playwright/test';
const email=process.env.E2E_ADMIN_EMAIL;const password=process.env.E2E_ADMIN_PASSWORD;
test.skip(!email||!password,'Set E2E_ADMIN_EMAIL and E2E_ADMIN_PASSWORD to run protected flows.');
test('admin can manage content without leaking private data',async({page})=>{
  await page.goto('/admin');await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill('definitely-wrong');await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByRole('alert')).toContainText('Invalid email or password');
  await page.getByLabel('Email').fill(email!);await page.getByLabel('Password').fill(password!);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');

  const upload=page.locator('form[action="?/photoUpload"]');await upload.locator('[name=photos]').setInputFiles('static/demo/road.png');await upload.locator('[name=display_date]').fill('2026-08-28');await upload.locator('[name=caption]').fill('E2E upload');await upload.locator('[name=alt_text]').fill('Test road through fields');await upload.locator('[name=visibility]').selectOption('public');await upload.getByRole('button',{name:/Upload photo/}).click();await expect(page.getByRole('status')).toContainText('Uploaded 1 photo');
  await page.goto('/photos');await expect(page.getByText('E2E upload',{exact:true})).toBeVisible();

  await page.goto('/admin?tab=photos');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');let item=page.locator('.admin-item').filter({hasText:'E2E upload'}).first();await item.locator('summary').click();await item.getByLabel('Caption').fill('E2E edited caption');await item.getByLabel('Visibility').selectOption('private');await item.getByRole('button',{name:'Save changes'}).click();
  await page.goto('/photos');await expect(page.getByText('E2E edited caption',{exact:true})).toHaveCount(0);
  await page.goto('/admin?tab=photos');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');item=page.locator('.admin-item').filter({hasText:'E2E edited caption'}).first();await item.locator('summary').click();await item.getByLabel('Visibility').selectOption('public');await item.getByRole('button',{name:'Save changes'}).click();await page.goto('/photos');await expect(page.getByText('E2E edited caption',{exact:true}).first()).toBeVisible();

  await page.goto('/admin?tab=now');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');const original=await page.getByLabel('Working on').inputValue();await page.getByLabel('Working on').fill('E2E temporary Now update');await page.getByRole('button',{name:'Save Now page'}).click();await expect(page.getByRole('status')).toContainText('Now page updated');await page.goto('/now');await expect(page.getByText('E2E temporary Now update')).toBeVisible();await page.goto('/admin?tab=now');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');await page.getByLabel('Working on').fill(original);await page.getByRole('button',{name:'Save Now page'}).click();

  await page.goto('/admin?tab=log');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');let create=page.locator('form[action="?/logSave"]').first();await create.locator('[name=event_date]').fill('2026-08-28T12:00');await create.locator('[name=title]').fill('E2E public log');await create.locator('[name=visibility]').selectOption('public');await create.getByRole('button',{name:'Create entry'}).click();await page.goto('/log');await expect(page.getByText('E2E public log',{exact:true})).toBeVisible();
  await page.goto('/admin?tab=log');await expect(page.locator('.admin-shell')).toHaveAttribute('data-hydrated','true');create=page.locator('form[action="?/logSave"]').first();await create.locator('[name=event_date]').fill('2026-08-28T12:01');await create.locator('[name=title]').fill('E2E private log');await create.locator('[name=visibility]').selectOption('private');await create.getByRole('button',{name:'Create entry'}).click();await page.goto('/log');await expect(page.getByText('E2E private log',{exact:true})).toHaveCount(0);

  page.on('dialog',(dialog)=>dialog.accept());for(const title of ['E2E public log','E2E private log']){await page.goto('/admin?tab=log');const row=page.locator('details.ledger-row').filter({hasText:title}).first();await row.locator('summary').click();await row.getByRole('button',{name:'Delete'}).click();}
  await page.goto('/admin?tab=photos');item=page.locator('.admin-item').filter({hasText:'E2E edited caption'});await item.locator('summary').click();await item.getByRole('button',{name:'Delete photo'}).click();await page.goto('/photos');await expect(page.getByText('E2E edited caption',{exact:true})).toHaveCount(0);
});
