import { fail, redirect } from '@sveltejs/kit';
import { dev } from '$app/environment';
import type { Actions } from './$types';
import type { RowDataPacket } from 'mysql2';
import { execute, rows } from '$lib/server/db';
import { createSession, destroySession } from '$lib/server/auth/session';
import { verifyPassword } from '$lib/server/auth/password';
import { clearFailures, loginAllowed, recordFailure } from '$lib/server/auth/throttle';
import { localStorage, UploadError } from '$lib/server/storage';
import type { Photo } from '$lib/server/models';

const text=(data:FormData,key:string)=>String(data.get(key)??'').trim();
const nullable=(data:FormData,key:string)=>text(data,key)||null;
const visibility=(data:FormData)=>text(data,'visibility')==='public'?'public':'private';
const validURL=(value:string,protocols:string[])=>{try{return protocols.includes(new URL(value).protocol);}catch{return false;}};
const requireAdmin=(locals:App.Locals)=>{if(!locals.admin)redirect(303,'/admin');return locals.admin;};
async function albumId(name:string|null){if(!name)return null;const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');await execute('INSERT INTO albums(name,slug) VALUES(?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)',[name,slug]);const result=await rows<RowDataPacket&{id:number}>('SELECT id FROM albums WHERE slug=?',[slug]);return result[0].id;}

export async function load({locals,url,setHeaders}){
  setHeaders({'Cache-Control':'private, no-store'});
  if(!locals.admin){const count=await rows<RowDataPacket&{count:number}>('SELECT COUNT(*) count FROM admin_users');return {admin:null,tab:'login',needsAdmin:dev&&count[0].count===0,photos:[] as Photo[],now:{working_on:'',learning:'',lately:''},logs:[],about:{intro:'',extended_text:null,portrait_photo_id:null},links:[],settings:{hero_photo_id:null,hero_headline:'',hero_copy:'',footer_text:'',footer_contact:null,photo_hero_id:null}};}
  const action=[...url.searchParams.keys()].find((key)=>key.startsWith('/'))?.slice(1)??'';const actionTabs:Record<string,string>={photoUpload:'photos',photoUpdate:'photos',photoDelete:'photos',nowSave:'now',logSave:'log',logDelete:'log',aboutSave:'about',linkAdd:'about',linkDelete:'about',settingsSave:'settings'};const requested=url.searchParams.get('tab')??actionTabs[action];const tab=['photos','now','log','about','settings'].includes(requested??'')?requested!:'photos';
  const [photos,now,logs,about,links,settings]=await Promise.all([
    rows<RowDataPacket & Photo>('SELECT p.*,a.name album_name FROM photos p LEFT JOIN albums a ON a.id=p.album_id ORDER BY COALESCE(p.display_date,p.created_at) DESC'),
    rows<RowDataPacket>('SELECT * FROM now_content WHERE id=1'),rows<RowDataPacket>('SELECT * FROM log_entries ORDER BY event_date DESC'),
    rows<RowDataPacket>('SELECT * FROM about_content WHERE id=1'),rows<RowDataPacket>('SELECT * FROM about_links ORDER BY sort_order,id'),rows<RowDataPacket>('SELECT * FROM site_settings WHERE id=1')]);
  return {admin:locals.admin,needsAdmin:false,tab,photos,now:now[0],logs,about:about[0],links,settings:settings[0]};
}

export const actions:Actions={
  login:async({request,cookies,getClientAddress})=>{const data=await request.formData();const email=text(data,'email').toLowerCase();const password=text(data,'password');const key=`${getClientAddress()}:${email}`;if(!loginAllowed(key))return fail(429,{loginError:'Invalid email or password. Please wait and try again.'});const found=await rows<RowDataPacket&{id:number;password_hash:string}>('SELECT id,password_hash FROM admin_users WHERE email=?',[email]);if(!found[0]||!(await verifyPassword(password,found[0].password_hash))){recordFailure(key);return fail(400,{loginError:'Invalid email or password.'});}clearFailures(key);await createSession(found[0].id,cookies);redirect(303,'/admin');},
  logout:async({locals,cookies})=>{requireAdmin(locals);await destroySession(cookies);redirect(303,'/admin');},
  photoUpload:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();const files=data.getAll('photos').filter((v):v is File=>v instanceof File&&v.size>0);if(!files.length)return fail(400,{formError:'Choose at least one image.'});const album=await albumId(nullable(data,'album'));let uploaded=0;const errors:string[]=[];for(const file of files){let key:string|null=null;try{const saved=await localStorage.save(file);key=saved.key;await execute(`INSERT INTO photos(storage_key,original_filename,mime_type,display_date,caption,note,place,album_id,alt_text,visibility,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[key,file.name.slice(0,500),file.type,nullable(data,'display_date'),nullable(data,'caption'),nullable(data,'note'),nullable(data,'place'),album,nullable(data,'alt_text'),visibility(data),nullable(data,'sort_order')]);uploaded++;}catch(error){if(key)await localStorage.delete(key).catch(console.error);errors.push(error instanceof UploadError?error.message:'An image could not be saved.');}}if(!uploaded)return fail(400,{formError:errors[0]??'Upload failed.'});return {success:`Uploaded ${uploaded} photo${uploaded===1?'':'s'}.${errors.length?' Some files were rejected.':''}`};},
  photoUpdate:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();const id=Number(text(data,'id'));if(!id)return fail(400,{formError:'Invalid photo.'});await execute(`UPDATE photos SET display_date=?,caption=?,note=?,place=?,album_id=?,alt_text=?,visibility=?,sort_order=? WHERE id=?`,[nullable(data,'display_date'),nullable(data,'caption'),nullable(data,'note'),nullable(data,'place'),await albumId(nullable(data,'album')),nullable(data,'alt_text'),visibility(data),nullable(data,'sort_order'),id]);return {success:'Photo updated.'};},
  photoDelete:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();const id=Number(text(data,'id'));const found=await rows<RowDataPacket&{storage_key:string}>('SELECT storage_key FROM photos WHERE id=?',[id]);if(!found[0])return fail(404,{formError:'Photo not found.'});await execute('DELETE FROM photos WHERE id=?',[id]);try{await localStorage.delete(found[0].storage_key);}catch(error){console.error('Photo metadata deleted, storage cleanup failed',error);return {success:'Photo deleted; its storage file could not be removed automatically.'};}return {success:'Photo deleted.'};},
  nowSave:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();await execute('UPDATE now_content SET working_on=?,learning=?,lately=? WHERE id=1',[text(data,'working_on'),text(data,'learning'),text(data,'lately')]);return {success:'Now page updated.'};},
  logSave:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();const id=Number(text(data,'id'));const title=text(data,'title'),event=nullable(data,'event_date');if(!title||!event)return fail(400,{formError:'Date and title are required.'});const url=nullable(data,'related_url');if(url&&!validURL(url,['http:','https:']))return fail(400,{formError:'Related URL must be an http(s) URL.'});const values=[event,title,nullable(data,'description'),url,nullable(data,'photo_id'),visibility(data)];if(id)await execute('UPDATE log_entries SET event_date=?,title=?,description=?,related_url=?,photo_id=?,visibility=? WHERE id=?',[...values,id]);else await execute('INSERT INTO log_entries(event_date,title,description,related_url,photo_id,visibility) VALUES(?,?,?,?,?,?)',values);return {success:id?'Log entry updated.':'Log entry created.'};},
  logDelete:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();await execute('DELETE FROM log_entries WHERE id=?',[Number(text(data,'id'))]);return {success:'Log entry deleted.'};},
  aboutSave:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();await execute('UPDATE about_content SET intro=?,extended_text=?,portrait_photo_id=? WHERE id=1',[text(data,'intro'),nullable(data,'extended_text'),nullable(data,'portrait_photo_id')]);return {success:'About page updated.'};},
  linkAdd:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();const label=text(data,'label'),url=text(data,'url');if(!validURL(url,['http:','https:','mailto:']))return fail(400,{formError:'Enter a complete web or email URL.'});await execute('INSERT INTO about_links(label,url,sort_order) VALUES(?,?,?)',[label,url,Number(text(data,'sort_order')||0)]);return {success:'Link added.'};},
  linkDelete:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();await execute('DELETE FROM about_links WHERE id=?',[Number(text(data,'id'))]);return {success:'Link deleted.'};},
  settingsSave:async({request,locals})=>{requireAdmin(locals);const data=await request.formData();await execute('UPDATE site_settings SET hero_photo_id=?,hero_headline=?,hero_copy=?,footer_text=?,footer_contact=?,photo_hero_id=? WHERE id=1',[nullable(data,'hero_photo_id'),text(data,'hero_headline'),text(data,'hero_copy'),text(data,'footer_text'),nullable(data,'footer_contact'),nullable(data,'photo_hero_id')]);return {success:'Site settings updated.'};}
};
