<script lang="ts">
  import { enhance } from '$app/forms';
  import { onMount } from 'svelte';
  import PhotoImage from '$lib/components/PhotoImage.svelte';
  import { inputDate, inputDateTime, dateLabel } from '$lib/format';
  let {data,form}=$props();
  let previews=$state<string[]>([]);
  let ready=$state(false);onMount(()=>ready=true);
  function preview(event:Event){previews.forEach(URL.revokeObjectURL);previews=Array.from((event.currentTarget as HTMLInputElement).files??[]).map(URL.createObjectURL);}
</script>
<svelte:head><title>Private — Westin Perry</title><meta name="robots" content="noindex,nofollow"/></svelte:head>
{#if !data.admin}
  <section class="login"><p class="eyebrow">Private</p><h1>Welcome back.</h1>{#if data.needsAdmin}<p class="notice">No local admin exists yet. In a terminal, run <code>npm run admin:create</code>, then sign in here.</p>{/if}<form class="stack" method="POST" action="?/login" use:enhance><label>Email<input name="email" type="email" autocomplete="username" required/></label><label>Password<input name="password" type="password" autocomplete="current-password" required/></label>{#if form?.loginError}<p class="error" role="alert">{form.loginError}</p>{/if}<button>Sign in</button></form></section>
{:else}
  <section class="admin-shell" data-hydrated={ready}><header class="admin-head"><div><p class="eyebrow">Private archive</p><h1>Site editor</h1></div><form method="POST" action="?/logout"><button class="subtle">Log out</button></form></header>
  <nav class="admin-tabs" aria-label="Admin sections">{#each [['photos','Photos'],['now','Now'],['log','Log'],['about','About'],['settings','Site Settings']] as tab}<a class:active={data.tab===tab[0]} href={`/admin?tab=${tab[0]}`}>{tab[1]}</a>{/each}</nav>
  {#if form?.formError}<p class="error" role="alert">{form.formError}</p>{/if}{#if form?.success}<p class="success" role="status">{form.success}</p>{/if}
  {#if data.tab==='photos'}
    <h2>Photos</h2><form class="form-grid" method="POST" action="?/photoUpload" enctype="multipart/form-data"><label class="full">Images<input name="photos" type="file" accept="image/jpeg,image/png,image/webp" multiple required onchange={preview}/></label>{#if previews.length}<div class="full" style="display:flex;gap:1rem;overflow:auto">{#each previews as src}<img src={src} alt="Upload preview" style="height:140px;width:auto"/>{/each}</div>{/if}<label>Display date<input name="display_date" type="date"/></label><label>Visibility<select name="visibility"><option value="public">Public</option><option value="private" selected>Private</option></select></label><label class="full">Caption<textarea name="caption"></textarea></label><label class="full">Longer note<textarea name="note"></textarea></label><label>Place<input name="place"/></label><label>Album<input name="album"/></label><label class="full">Alt text<input name="alt_text" placeholder="Describe the image for someone who cannot see it"/></label><label>Manual sort override<input name="sort_order" type="number"/></label><div><button>Upload photo{previews.length===1?'':'s'}</button></div></form>
    <div class="admin-list">{#each data.photos as photo}<article class="admin-item"><PhotoImage class="admin-thumb" {photo}/><div><strong>{photo.caption||photo.original_filename}</strong><br/><span class="meta">{dateLabel(photo.display_date)} · {photo.visibility}</span></div><details><summary>Edit</summary><form class="stack" method="POST" action="?/photoUpdate"><input type="hidden" name="id" value={photo.id}/><label>Date<input name="display_date" type="date" value={inputDate(photo.display_date)}/></label><label>Caption<textarea name="caption">{photo.caption??''}</textarea></label><label>Long note<textarea name="note">{photo.note??''}</textarea></label><label>Place<input name="place" value={photo.place??''}/></label><label>Album<input name="album" value={photo.album_name??''}/></label><label>Alt text<input name="alt_text" value={photo.alt_text??''}/></label><label>Visibility<select name="visibility" value={photo.visibility}><option value="public">Public</option><option value="private">Private</option></select></label><label>Sort<input name="sort_order" type="number" value={photo.sort_order??''}/></label><button>Save changes</button></form><form method="POST" action="?/photoDelete" onsubmit={(e)=>{if(!confirm('Delete this photo permanently?'))e.preventDefault()}}><input type="hidden" name="id" value={photo.id}/><button class="danger">Delete photo</button></form></details></article>{/each}</div>
  {:else if data.tab==='now'}
    <h2>Now</h2><form class="stack" method="POST" action="?/nowSave"><label>Working on<textarea name="working_on" required>{data.now.working_on}</textarea></label><label>Learning<textarea name="learning" required>{data.now.learning}</textarea></label><label>Lately<textarea name="lately" required>{data.now.lately}</textarea></label><button>Save Now page</button></form>
  {:else if data.tab==='log'}
    <h2>Log</h2><form class="form-grid" method="POST" action="?/logSave"><label>Date and time<input type="datetime-local" name="event_date" required/></label><label>Visibility<select name="visibility"><option value="public">Public</option><option value="private" selected>Private</option></select></label><label class="full">Title<input name="title" required/></label><label class="full">Description<textarea name="description"></textarea></label><label>Related URL<input name="related_url" type="url"/></label><label>Related photo<select name="photo_id"><option value="">None</option>{#each data.photos as photo}<option value={photo.id}>{photo.caption||photo.original_filename}</option>{/each}</select></label><button>Create entry</button></form>
    <div class="admin-list">{#each data.logs as entry}<details class="ledger-row"><summary><span class="meta">{dateLabel(entry.event_date)}</span> — {entry.title} ({entry.visibility})</summary><form class="form-grid" method="POST" action="?/logSave"><input type="hidden" name="id" value={entry.id}/><label>Date<input name="event_date" type="datetime-local" value={inputDateTime(entry.event_date)} required/></label><label>Visibility<select name="visibility" value={entry.visibility}><option value="public">Public</option><option value="private">Private</option></select></label><label class="full">Title<input name="title" value={entry.title} required/></label><label class="full">Description<textarea name="description">{entry.description??''}</textarea></label><label>URL<input name="related_url" type="url" value={entry.related_url??''}/></label><label>Photo<select name="photo_id" value={entry.photo_id??''}><option value="">None</option>{#each data.photos as photo}<option value={photo.id}>{photo.caption||photo.original_filename}</option>{/each}</select></label><button>Save entry</button></form><form method="POST" action="?/logDelete" onsubmit={(e)=>{if(!confirm('Delete this log entry?'))e.preventDefault()}}><input type="hidden" name="id" value={entry.id}/><button class="danger">Delete</button></form></details>{/each}</div>
  {:else if data.tab==='about'}
    <h2>About</h2><form class="stack" method="POST" action="?/aboutSave"><label>Short introduction<textarea name="intro" required>{data.about.intro}</textarea></label><label>Longer paragraph<textarea name="extended_text">{data.about.extended_text??''}</textarea></label><label>Portrait<select name="portrait_photo_id" value={data.about.portrait_photo_id??''}><option value="">No portrait</option>{#each data.photos as photo}<option value={photo.id}>{photo.caption||photo.original_filename}</option>{/each}</select></label><button>Save About page</button></form><h3 style="margin-top:4rem">Elsewhere links</h3><form class="form-grid" method="POST" action="?/linkAdd"><label>Label<input name="label" required/></label><label>URL<input name="url" type="url" required/></label><label>Order<input name="sort_order" type="number" value="0"/></label><button>Add link</button></form><div class="admin-list">{#each data.links as link}<div class="ledger-row"><a href={link.url}>{link.label}</a><form method="POST" action="?/linkDelete"><input type="hidden" name="id" value={link.id}/><button class="danger">Delete</button></form></div>{/each}</div>
  {:else}
    <h2>Site Settings</h2><form class="stack" method="POST" action="?/settingsSave"><label>Homepage hero image<select name="hero_photo_id" value={data.settings.hero_photo_id??''}><option value="">None</option>{#each data.photos as photo}<option value={photo.id}>{photo.caption||photo.original_filename}</option>{/each}</select></label><label>Hero headline<textarea name="hero_headline" required>{data.settings.hero_headline}</textarea></label><label>Hero supporting copy<textarea name="hero_copy" required>{data.settings.hero_copy}</textarea></label><label>Photo-page hero image<select name="photo_hero_id" value={data.settings.photo_hero_id??''}><option value="">None</option>{#each data.photos as photo}<option value={photo.id}>{photo.caption||photo.original_filename}</option>{/each}</select></label><label>Footer text<input name="footer_text" value={data.settings.footer_text} required/></label><label>Footer email or URL<input name="footer_contact" value={data.settings.footer_contact??''}/></label><button>Save settings</button></form>
  {/if}</section>
{/if}
